[2025-02-17 19:03:47,549][flwr][INFO] - Starting Flower ServerApp, config: num_rounds=20, no round_timeout
[2025-02-17 19:03:47,551][flwr][INFO] - 
[2025-02-17 19:03:47,554][flwr][INFO] - [INIT]
[2025-02-17 19:03:47,554][flwr][INFO] - Using initial global parameters provided by strategy
[2025-02-17 19:03:47,554][flwr][INFO] - Starting evaluation of initial global parameters
[2025-02-17 19:03:55,837][flwr][INFO] - initial parameters (loss, other metrics): 0.07214015040397644, {'accuracy': 0.0988}
[2025-02-17 19:03:55,837][flwr][INFO] - 
[2025-02-17 19:03:55,837][flwr][INFO] - [ROUND 1]
[2025-02-17 19:03:55,838][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 19:04:07,167][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 19:04:13,436][flwr][INFO] - fit progress: (1, 0.07179670739173889, {'accuracy': 0.0995}, 17.598826368979644)
[2025-02-17 19:04:13,436][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 19:04:17,849][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 19:04:17,849][flwr][INFO] - 
[2025-02-17 19:04:17,849][flwr][INFO] - [ROUND 2]
[2025-02-17 19:04:17,849][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 19:04:23,161][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 19:04:27,605][flwr][INFO] - fit progress: (2, 0.06997157254219055, {'accuracy': 0.1796}, 31.767191953986185)
[2025-02-17 19:04:27,605][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 19:04:32,016][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 19:04:32,016][flwr][INFO] - 
[2025-02-17 19:04:32,017][flwr][INFO] - [ROUND 3]
[2025-02-17 19:04:32,017][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 19:04:37,229][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 19:04:41,757][flwr][INFO] - fit progress: (3, 0.06748134216070176, {'accuracy': 0.2217}, 45.91951066299225)
[2025-02-17 19:04:41,757][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 19:04:46,067][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 19:04:46,067][flwr][INFO] - 
[2025-02-17 19:04:46,067][flwr][INFO] - [ROUND 4]
[2025-02-17 19:04:46,068][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 19:04:51,480][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 19:04:56,056][flwr][INFO] - fit progress: (4, 0.06667252056598663, {'accuracy': 0.3083}, 60.21821281098528)
[2025-02-17 19:04:56,056][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 19:05:19,889][flwr][ERROR] - An exception was raised when processing a message by RayBackend
[2025-02-17 19:05:19,889][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=12347, ip=172.27.85.201, actor_id=5f62357b6010f638c71c149c01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f73841c6ed0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=12347, ip=172.27.85.201, actor_id=5f62357b6010f638c71c149c01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f73841c6ed0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 201, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=12347, ip=172.27.85.201, actor_id=5f62357b6010f638c71c149c01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f73841c6ed0>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c
[2025-02-17 19:05:19,891][flwr][ERROR] - Traceback (most recent call last):
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py", line 112, in worker
    out_mssg, updated_context = backend.process_message(message, context)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 187, in process_message
    raise ex
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 175, in process_message
    ) = self.pool.fetch_result_and_return_actor_to_pool(future)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 478, in fetch_result_and_return_actor_to_pool
    _, out_mssg, updated_context = ray.get(future)
                                   ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=12347, ip=172.27.85.201, actor_id=5f62357b6010f638c71c149c01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f73841c6ed0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=12347, ip=172.27.85.201, actor_id=5f62357b6010f638c71c149c01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f73841c6ed0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 201, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=12347, ip=172.27.85.201, actor_id=5f62357b6010f638c71c149c01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f73841c6ed0>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

[2025-02-17 19:05:19,897][flwr][INFO] - aggregate_evaluate: received 9 results and 1 failures
[2025-02-17 19:05:19,898][flwr][INFO] - 
[2025-02-17 19:05:19,898][flwr][INFO] - [ROUND 5]
[2025-02-17 19:05:19,898][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 19:05:32,235][flwr][ERROR] - An exception was raised when processing a message by RayBackend
[2025-02-17 19:05:32,235][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=12344, ip=172.27.85.201, actor_id=bc4660afbde122aa7aa26d0b01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fc78c13db10>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=12344, ip=172.27.85.201, actor_id=bc4660afbde122aa7aa26d0b01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fc78c13db10>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 201, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=12344, ip=172.27.85.201, actor_id=bc4660afbde122aa7aa26d0b01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fc78c13db10>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c
[2025-02-17 19:05:32,235][flwr][ERROR] - Traceback (most recent call last):
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py", line 112, in worker
    out_mssg, updated_context = backend.process_message(message, context)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 187, in process_message
    raise ex
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 175, in process_message
    ) = self.pool.fetch_result_and_return_actor_to_pool(future)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 478, in fetch_result_and_return_actor_to_pool
    _, out_mssg, updated_context = ray.get(future)
                                   ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=12344, ip=172.27.85.201, actor_id=bc4660afbde122aa7aa26d0b01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fc78c13db10>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=12344, ip=172.27.85.201, actor_id=bc4660afbde122aa7aa26d0b01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fc78c13db10>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 201, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=12344, ip=172.27.85.201, actor_id=bc4660afbde122aa7aa26d0b01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fc78c13db10>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

[2025-02-17 19:05:44,149][flwr][INFO] - aggregate_fit: received 9 results and 1 failures
[2025-02-17 19:05:48,734][flwr][INFO] - fit progress: (5, 0.09231852786540985, {'accuracy': 0.3474}, 112.89651333398069)
[2025-02-17 19:05:48,734][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 19:05:52,644][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 19:05:52,644][flwr][INFO] - 
[2025-02-17 19:05:52,644][flwr][INFO] - [ROUND 6]
[2025-02-17 19:05:52,645][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 19:05:58,157][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 19:06:02,395][flwr][INFO] - fit progress: (6, 0.15730340120792388, {'accuracy': 0.3617}, 126.55729036798584)
[2025-02-17 19:06:02,395][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 19:06:06,906][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 19:06:06,906][flwr][INFO] - 
[2025-02-17 19:06:06,906][flwr][INFO] - [ROUND 7]
[2025-02-17 19:06:06,906][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 19:06:12,321][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 19:06:16,975][flwr][INFO] - fit progress: (7, 0.2823376217842102, {'accuracy': 0.3618}, 141.13776639700518)
[2025-02-17 19:06:16,975][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 19:06:20,984][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 19:06:20,984][flwr][INFO] - 
[2025-02-17 19:06:20,984][flwr][INFO] - [ROUND 8]
[2025-02-17 19:06:20,985][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 19:06:27,298][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 19:06:34,341][flwr][INFO] - fit progress: (8, 0.49665838737487794, {'accuracy': 0.3501}, 158.50395282299723)
[2025-02-17 19:06:34,341][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 19:06:38,750][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 19:06:38,751][flwr][INFO] - 
[2025-02-17 19:06:38,751][flwr][INFO] - [ROUND 9]
[2025-02-17 19:06:38,751][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 19:06:44,765][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 19:06:49,179][flwr][INFO] - fit progress: (9, 0.8439452177047729, {'accuracy': 0.3338}, 173.34203984899796)
[2025-02-17 19:06:49,180][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 19:06:53,188][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 19:06:53,188][flwr][INFO] - 
[2025-02-17 19:06:53,188][flwr][INFO] - [ROUND 10]
[2025-02-17 19:06:53,188][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 19:06:58,699][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 19:07:03,447][flwr][INFO] - fit progress: (10, 1.3803366899490357, {'accuracy': 0.322}, 187.6101314970001)
[2025-02-17 19:07:03,448][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 19:07:07,557][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 19:07:07,557][flwr][INFO] - 
[2025-02-17 19:07:07,558][flwr][INFO] - [ROUND 11]
[2025-02-17 19:07:07,558][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 19:07:12,970][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 19:07:17,179][flwr][INFO] - fit progress: (11, 2.1733484825134277, {'accuracy': 0.3055}, 201.34126744099194)
[2025-02-17 19:07:17,179][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 19:07:22,391][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 19:07:22,391][flwr][INFO] - 
[2025-02-17 19:07:22,391][flwr][INFO] - [ROUND 12]
[2025-02-17 19:07:22,391][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 19:07:27,903][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 19:07:32,183][flwr][INFO] - fit progress: (12, 3.290089728927612, {'accuracy': 0.2977}, 216.34614271798637)
[2025-02-17 19:07:32,184][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 19:07:39,497][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 19:07:39,497][flwr][INFO] - 
[2025-02-17 19:07:39,497][flwr][INFO] - [ROUND 13]
[2025-02-17 19:07:39,497][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 19:07:44,709][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 19:07:49,148][flwr][INFO] - fit progress: (13, 4.82711067276001, {'accuracy': 0.2908}, 233.31065289699472)
[2025-02-17 19:07:49,148][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 19:07:53,057][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 19:07:53,058][flwr][INFO] - 
[2025-02-17 19:07:53,058][flwr][INFO] - [ROUND 14]
[2025-02-17 19:07:53,058][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 19:07:58,371][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 19:08:32,484][flwr][INFO] - fit progress: (14, 6.8907409759521485, {'accuracy': 0.2865}, 276.6470168439846)
[2025-02-17 19:08:32,485][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 19:08:36,593][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 19:08:36,593][flwr][INFO] - 
[2025-02-17 19:08:36,593][flwr][INFO] - [ROUND 15]
[2025-02-17 19:08:36,593][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 19:08:41,904][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 19:08:46,029][flwr][INFO] - fit progress: (15, 9.610236415100097, {'accuracy': 0.2838}, 290.19186937398626)
[2025-02-17 19:08:46,029][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 19:08:50,639][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 19:08:50,639][flwr][INFO] - 
[2025-02-17 19:08:50,639][flwr][INFO] - [ROUND 16]
[2025-02-17 19:08:50,639][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 19:08:56,153][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 19:09:02,112][flwr][INFO] - fit progress: (16, 13.134195281982421, {'accuracy': 0.2817}, 306.2751768529997)
[2025-02-17 19:09:02,113][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 19:09:06,623][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 19:09:06,624][flwr][INFO] - 
[2025-02-17 19:09:06,624][flwr][INFO] - [ROUND 17]
[2025-02-17 19:09:06,624][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 19:09:12,036][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 19:09:16,206][flwr][INFO] - fit progress: (17, 17.603136865234376, {'accuracy': 0.2781}, 320.3689179329958)
[2025-02-17 19:09:16,206][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 19:09:20,717][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 19:09:20,717][flwr][INFO] - 
[2025-02-17 19:09:20,718][flwr][INFO] - [ROUND 18]
[2025-02-17 19:09:20,718][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 19:09:25,929][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 19:09:30,115][flwr][INFO] - fit progress: (18, 23.200623815917968, {'accuracy': 0.2751}, 334.2779260079842)
[2025-02-17 19:09:30,115][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 19:09:34,124][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 19:09:34,124][flwr][INFO] - 
[2025-02-17 19:09:34,125][flwr][INFO] - [ROUND 19]
[2025-02-17 19:09:34,125][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 19:09:39,437][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 19:09:43,661][flwr][INFO] - fit progress: (19, 30.143182159423827, {'accuracy': 0.2749}, 347.8234020349919)
[2025-02-17 19:09:43,661][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 19:09:49,473][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 19:09:49,474][flwr][INFO] - 
[2025-02-17 19:09:49,474][flwr][INFO] - [ROUND 20]
[2025-02-17 19:09:49,474][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 19:09:54,785][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 19:10:00,031][flwr][INFO] - fit progress: (20, 38.61189253540039, {'accuracy': 0.2727}, 364.19370046799304)
[2025-02-17 19:10:00,031][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 19:10:04,340][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 19:10:04,340][flwr][INFO] - 
[2025-02-17 19:10:04,340][flwr][INFO] - [SUMMARY]
[2025-02-17 19:10:04,340][flwr][INFO] - Run finished 20 round(s) in 368.50s
[2025-02-17 19:10:04,341][flwr][INFO] - 	History (loss, distributed):
[2025-02-17 19:10:04,341][flwr][INFO] - 		round 1: 0.07642418762048087
[2025-02-17 19:10:04,341][flwr][INFO] - 		round 2: 0.07469371696313223
[2025-02-17 19:10:04,341][flwr][INFO] - 		round 3: 0.07265907694896061
[2025-02-17 19:10:04,342][flwr][INFO] - 		round 4: 0.07366156092396488
[2025-02-17 19:10:04,342][flwr][INFO] - 		round 5: 0.1049728344877561
[2025-02-17 19:10:04,342][flwr][INFO] - 		round 6: 0.17801208953062692
[2025-02-17 19:10:04,342][flwr][INFO] - 		round 7: 0.31444923241933187
[2025-02-17 19:10:04,342][flwr][INFO] - 		round 8: 0.5486732319990792
[2025-02-17 19:10:04,342][flwr][INFO] - 		round 9: 0.9347855401039122
[2025-02-17 19:10:04,342][flwr][INFO] - 		round 10: 1.5313974905014036
[2025-02-17 19:10:04,342][flwr][INFO] - 		round 11: 2.410816354751587
[2025-02-17 19:10:04,342][flwr][INFO] - 		round 12: 3.6393185551961267
[2025-02-17 19:10:04,342][flwr][INFO] - 		round 13: 5.3234156990051265
[2025-02-17 19:10:04,342][flwr][INFO] - 		round 14: 7.585139859517414
[2025-02-17 19:10:04,342][flwr][INFO] - 		round 15: 10.549483248392741
[2025-02-17 19:10:04,342][flwr][INFO] - 		round 16: 14.387058003743487
[2025-02-17 19:10:04,343][flwr][INFO] - 		round 17: 19.26177655537923
[2025-02-17 19:10:04,343][flwr][INFO] - 		round 18: 25.377754338582356
[2025-02-17 19:10:04,343][flwr][INFO] - 		round 19: 32.95076746622721
[2025-02-17 19:10:04,343][flwr][INFO] - 		round 20: 42.1980133565267
[2025-02-17 19:10:04,343][flwr][INFO] - 	History (loss, centralized):
[2025-02-17 19:10:04,343][flwr][INFO] - 		round 0: 0.07214015040397644
[2025-02-17 19:10:04,343][flwr][INFO] - 		round 1: 0.07179670739173889
[2025-02-17 19:10:04,343][flwr][INFO] - 		round 2: 0.06997157254219055
[2025-02-17 19:10:04,343][flwr][INFO] - 		round 3: 0.06748134216070176
[2025-02-17 19:10:04,343][flwr][INFO] - 		round 4: 0.06667252056598663
[2025-02-17 19:10:04,343][flwr][INFO] - 		round 5: 0.09231852786540985
[2025-02-17 19:10:04,343][flwr][INFO] - 		round 6: 0.15730340120792388
[2025-02-17 19:10:04,343][flwr][INFO] - 		round 7: 0.2823376217842102
[2025-02-17 19:10:04,343][flwr][INFO] - 		round 8: 0.49665838737487794
[2025-02-17 19:10:04,344][flwr][INFO] - 		round 9: 0.8439452177047729
[2025-02-17 19:10:04,344][flwr][INFO] - 		round 10: 1.3803366899490357
[2025-02-17 19:10:04,344][flwr][INFO] - 		round 11: 2.1733484825134277
[2025-02-17 19:10:04,344][flwr][INFO] - 		round 12: 3.290089728927612
[2025-02-17 19:10:04,344][flwr][INFO] - 		round 13: 4.82711067276001
[2025-02-17 19:10:04,344][flwr][INFO] - 		round 14: 6.8907409759521485
[2025-02-17 19:10:04,344][flwr][INFO] - 		round 15: 9.610236415100097
[2025-02-17 19:10:04,344][flwr][INFO] - 		round 16: 13.134195281982421
[2025-02-17 19:10:04,344][flwr][INFO] - 		round 17: 17.603136865234376
[2025-02-17 19:10:04,344][flwr][INFO] - 		round 18: 23.200623815917968
[2025-02-17 19:10:04,344][flwr][INFO] - 		round 19: 30.143182159423827
[2025-02-17 19:10:04,344][flwr][INFO] - 		round 20: 38.61189253540039
[2025-02-17 19:10:04,344][flwr][INFO] - 	History (metrics, distributed, fit):
[2025-02-17 19:10:04,344][flwr][INFO] - 	{'clients_epsilons': [(1, 0.5),
[2025-02-17 19:10:04,345][flwr][INFO] - 	                      (2, 0.5),
[2025-02-17 19:10:04,345][flwr][INFO] - 	                      (3, 0.5),
[2025-02-17 19:10:04,345][flwr][INFO] - 	                      (4, 0.5),
[2025-02-17 19:10:04,345][flwr][INFO] - 	                      (5, 0.5),
[2025-02-17 19:10:04,345][flwr][INFO] - 	                      (6, 0.5),
[2025-02-17 19:10:04,345][flwr][INFO] - 	                      (7, 0.5),
[2025-02-17 19:10:04,345][flwr][INFO] - 	                      (8, 0.5),
[2025-02-17 19:10:04,345][flwr][INFO] - 	                      (9, 0.5),
[2025-02-17 19:10:04,345][flwr][INFO] - 	                      (10, 0.5),
[2025-02-17 19:10:04,345][flwr][INFO] - 	                      (11, 0.5),
[2025-02-17 19:10:04,345][flwr][INFO] - 	                      (12, 0.5),
[2025-02-17 19:10:04,345][flwr][INFO] - 	                      (13, 0.5),
[2025-02-17 19:10:04,345][flwr][INFO] - 	                      (14, 0.5),
[2025-02-17 19:10:04,346][flwr][INFO] - 	                      (15, 0.5),
[2025-02-17 19:10:04,346][flwr][INFO] - 	                      (16, 0.5),
[2025-02-17 19:10:04,346][flwr][INFO] - 	                      (17, 0.5),
[2025-02-17 19:10:04,346][flwr][INFO] - 	                      (18, 0.5),
[2025-02-17 19:10:04,346][flwr][INFO] - 	                      (19, 0.5),
[2025-02-17 19:10:04,346][flwr][INFO] - 	                      (20, 0.5)],
[2025-02-17 19:10:04,346][flwr][INFO] - 	 'clients_losses': [(1, 2.301679186820984),
[2025-02-17 19:10:04,346][flwr][INFO] - 	                    (2, 2.275116516749064),
[2025-02-17 19:10:04,346][flwr][INFO] - 	                    (3, 2.21167937596639),
[2025-02-17 19:10:04,346][flwr][INFO] - 	                    (4, 2.164822483062744),
[2025-02-17 19:10:04,346][flwr][INFO] - 	                    (5, 2.4877899169921873),
[2025-02-17 19:10:04,346][flwr][INFO] - 	                    (6, 3.878682089646657),
[2025-02-17 19:10:04,346][flwr][INFO] - 	                    (7, 6.746269834836324),
[2025-02-17 19:10:04,346][flwr][INFO] - 	                    (8, 11.944446376164754),
[2025-02-17 19:10:04,346][flwr][INFO] - 	                    (9, 20.593383401234945),
[2025-02-17 19:10:04,347][flwr][INFO] - 	                    (10, 34.39950870513916),
[2025-02-17 19:10:04,347][flwr][INFO] - 	                    (11, 55.229881057739256),
[2025-02-17 19:10:04,347][flwr][INFO] - 	                    (12, 85.21272918701172),
[2025-02-17 19:10:04,347][flwr][INFO] - 	                    (13, 126.94015869140625),
[2025-02-17 19:10:04,347][flwr][INFO] - 	                    (14, 183.5630398050944),
[2025-02-17 19:10:04,347][flwr][INFO] - 	                    (15, 258.8755359903971),
[2025-02-17 19:10:04,347][flwr][INFO] - 	                    (16, 356.8523485310872),
[2025-02-17 19:10:04,347][flwr][INFO] - 	                    (17, 482.05883626302085),
[2025-02-17 19:10:04,347][flwr][INFO] - 	                    (18, 640.4637113444011),
[2025-02-17 19:10:04,347][flwr][INFO] - 	                    (19, 837.7659110514323),
[2025-02-17 19:10:04,347][flwr][INFO] - 	                    (20, 1080.0299788411457)]}
[2025-02-17 19:10:04,348][flwr][INFO] - 	History (metrics, distributed, evaluate):
[2025-02-17 19:10:04,348][flwr][INFO] - 	{'clients_accuracies': [(1, 0.09833333333333334),
[2025-02-17 19:10:04,348][flwr][INFO] - 	                        (2, 0.1683333333333333),
[2025-02-17 19:10:04,348][flwr][INFO] - 	                        (3, 0.20749999999999996),
[2025-02-17 19:10:04,348][flwr][INFO] - 	                        (4, 0.2898148148148148),
[2025-02-17 19:10:04,348][flwr][INFO] - 	                        (5, 0.32916666666666666),
[2025-02-17 19:10:04,348][flwr][INFO] - 	                        (6, 0.3358333333333333),
[2025-02-17 19:10:04,348][flwr][INFO] - 	                        (7, 0.3283333333333333),
[2025-02-17 19:10:04,348][flwr][INFO] - 	                        (8, 0.32166666666666666),
[2025-02-17 19:10:04,348][flwr][INFO] - 	                        (9, 0.31166666666666665),
[2025-02-17 19:10:04,348][flwr][INFO] - 	                        (10, 0.29333333333333333),
[2025-02-17 19:10:04,348][flwr][INFO] - 	                        (11, 0.2816666666666667),
[2025-02-17 19:10:04,348][flwr][INFO] - 	                        (12, 0.2791666666666667),
[2025-02-17 19:10:04,349][flwr][INFO] - 	                        (13, 0.2708333333333333),
[2025-02-17 19:10:04,349][flwr][INFO] - 	                        (14, 0.2625),
[2025-02-17 19:10:04,349][flwr][INFO] - 	                        (15, 0.26000000000000006),
[2025-02-17 19:10:04,349][flwr][INFO] - 	                        (16, 0.25083333333333335),
[2025-02-17 19:10:04,349][flwr][INFO] - 	                        (17, 0.25),
[2025-02-17 19:10:04,349][flwr][INFO] - 	                        (18, 0.2525),
[2025-02-17 19:10:04,349][flwr][INFO] - 	                        (19, 0.25416666666666665),
[2025-02-17 19:10:04,349][flwr][INFO] - 	                        (20, 0.25166666666666665)],
[2025-02-17 19:10:04,349][flwr][INFO] - 	 'clients_losses': [(1, 0.07642418762048087),
[2025-02-17 19:10:04,349][flwr][INFO] - 	                    (2, 0.07469371696313223),
[2025-02-17 19:10:04,349][flwr][INFO] - 	                    (3, 0.07265907694896061),
[2025-02-17 19:10:04,349][flwr][INFO] - 	                    (4, 0.07366156092396488),
[2025-02-17 19:10:04,349][flwr][INFO] - 	                    (5, 0.1049728344877561),
[2025-02-17 19:10:04,349][flwr][INFO] - 	                    (6, 0.17801208953062692),
[2025-02-17 19:10:04,350][flwr][INFO] - 	                    (7, 0.31444923241933187),
[2025-02-17 19:10:04,350][flwr][INFO] - 	                    (8, 0.5486732319990792),
[2025-02-17 19:10:04,350][flwr][INFO] - 	                    (9, 0.9347855401039122),
[2025-02-17 19:10:04,350][flwr][INFO] - 	                    (10, 1.5313974905014036),
[2025-02-17 19:10:04,350][flwr][INFO] - 	                    (11, 2.410816354751587),
[2025-02-17 19:10:04,350][flwr][INFO] - 	                    (12, 3.6393185551961267),
[2025-02-17 19:10:04,350][flwr][INFO] - 	                    (13, 5.3234156990051265),
[2025-02-17 19:10:04,350][flwr][INFO] - 	                    (14, 7.585139859517414),
[2025-02-17 19:10:04,350][flwr][INFO] - 	                    (15, 10.549483248392741),
[2025-02-17 19:10:04,350][flwr][INFO] - 	                    (16, 14.387058003743487),
[2025-02-17 19:10:04,350][flwr][INFO] - 	                    (17, 19.26177655537923),
[2025-02-17 19:10:04,350][flwr][INFO] - 	                    (18, 25.377754338582356),
[2025-02-17 19:10:04,350][flwr][INFO] - 	                    (19, 32.95076746622721),
[2025-02-17 19:10:04,351][flwr][INFO] - 	                    (20, 42.1980133565267)]}
[2025-02-17 19:10:04,351][flwr][INFO] - 	History (metrics, centralized):
[2025-02-17 19:10:04,351][flwr][INFO] - 	{'accuracy': [(0, 0.0988),
[2025-02-17 19:10:04,351][flwr][INFO] - 	              (1, 0.0995),
[2025-02-17 19:10:04,351][flwr][INFO] - 	              (2, 0.1796),
[2025-02-17 19:10:04,351][flwr][INFO] - 	              (3, 0.2217),
[2025-02-17 19:10:04,351][flwr][INFO] - 	              (4, 0.3083),
[2025-02-17 19:10:04,351][flwr][INFO] - 	              (5, 0.3474),
[2025-02-17 19:10:04,351][flwr][INFO] - 	              (6, 0.3617),
[2025-02-17 19:10:04,351][flwr][INFO] - 	              (7, 0.3618),
[2025-02-17 19:10:04,351][flwr][INFO] - 	              (8, 0.3501),
[2025-02-17 19:10:04,351][flwr][INFO] - 	              (9, 0.3338),
[2025-02-17 19:10:04,351][flwr][INFO] - 	              (10, 0.322),
[2025-02-17 19:10:04,352][flwr][INFO] - 	              (11, 0.3055),
[2025-02-17 19:10:04,352][flwr][INFO] - 	              (12, 0.2977),
[2025-02-17 19:10:04,352][flwr][INFO] - 	              (13, 0.2908),
[2025-02-17 19:10:04,352][flwr][INFO] - 	              (14, 0.2865),
[2025-02-17 19:10:04,352][flwr][INFO] - 	              (15, 0.2838),
[2025-02-17 19:10:04,352][flwr][INFO] - 	              (16, 0.2817),
[2025-02-17 19:10:04,352][flwr][INFO] - 	              (17, 0.2781),
[2025-02-17 19:10:04,352][flwr][INFO] - 	              (18, 0.2751),
[2025-02-17 19:10:04,352][flwr][INFO] - 	              (19, 0.2749),
[2025-02-17 19:10:04,352][flwr][INFO] - 	              (20, 0.2727)]}
[2025-02-17 19:10:04,352][flwr][INFO] - 
