[2025-02-10 02:13:37,623][flwr][INFO] - Starting Flower ServerApp, config: num_rounds=20, no round_timeout
[2025-02-10 02:13:37,623][flwr][INFO] - 
[2025-02-10 02:13:37,624][flwr][INFO] - [INIT]
[2025-02-10 02:13:37,625][flwr][INFO] - Using initial global parameters provided by strategy
[2025-02-10 02:13:37,625][flwr][INFO] - Starting evaluation of initial global parameters
[2025-02-10 02:13:45,296][flwr][INFO] - initial parameters (loss, other metrics): 0.07214015040397644, {'accuracy': 0.0988}
[2025-02-10 02:13:45,297][flwr][INFO] - 
[2025-02-10 02:13:45,297][flwr][INFO] - [ROUND 1]
[2025-02-10 02:13:45,297][flwr][INFO] - configure_fit: strategy sampled 20 clients (out of 20)
[2025-02-10 02:14:16,148][flwr][INFO] - aggregate_fit: received 20 results and 0 failures
[2025-02-10 02:14:21,527][flwr][INFO] - fit progress: (1, 0.07187389771938324, {'accuracy': 0.1655}, 36.23042350399919)
[2025-02-10 02:14:21,527][flwr][INFO] - configure_evaluate: strategy sampled 20 clients (out of 20)
[2025-02-10 02:14:47,602][flwr][INFO] - aggregate_evaluate: received 20 results and 0 failures
[2025-02-10 02:14:47,602][flwr][INFO] - 
[2025-02-10 02:14:47,602][flwr][INFO] - [ROUND 2]
[2025-02-10 02:14:47,603][flwr][INFO] - configure_fit: strategy sampled 20 clients (out of 20)
[2025-02-10 02:15:13,290][flwr][INFO] - aggregate_fit: received 20 results and 0 failures
[2025-02-10 02:15:19,205][flwr][INFO] - fit progress: (2, 0.07153169589042664, {'accuracy': 0.1957}, 93.90820099499979)
[2025-02-10 02:15:19,205][flwr][INFO] - configure_evaluate: strategy sampled 20 clients (out of 20)
[2025-02-10 02:15:43,678][flwr][INFO] - aggregate_evaluate: received 20 results and 0 failures
[2025-02-10 02:15:43,678][flwr][INFO] - 
[2025-02-10 02:15:43,678][flwr][INFO] - [ROUND 3]
[2025-02-10 02:15:43,679][flwr][INFO] - configure_fit: strategy sampled 20 clients (out of 20)
[2025-02-10 02:16:09,267][flwr][INFO] - aggregate_fit: received 20 results and 0 failures
[2025-02-10 02:16:14,959][flwr][INFO] - fit progress: (3, 0.07093953688144684, {'accuracy': 0.2046}, 149.66225001499697)
[2025-02-10 02:16:14,959][flwr][INFO] - configure_evaluate: strategy sampled 20 clients (out of 20)
[2025-02-10 02:16:38,294][flwr][INFO] - aggregate_evaluate: received 20 results and 0 failures
[2025-02-10 02:16:38,294][flwr][INFO] - 
[2025-02-10 02:16:38,295][flwr][INFO] - [ROUND 4]
[2025-02-10 02:16:38,295][flwr][INFO] - configure_fit: strategy sampled 20 clients (out of 20)
[2025-02-10 02:17:04,432][flwr][INFO] - aggregate_fit: received 20 results and 0 failures
[2025-02-10 02:17:10,363][flwr][INFO] - fit progress: (4, 0.06998767564296722, {'accuracy': 0.3171}, 205.06618556399917)
[2025-02-10 02:17:10,363][flwr][INFO] - configure_evaluate: strategy sampled 20 clients (out of 20)
[2025-02-10 02:17:33,812][flwr][INFO] - aggregate_evaluate: received 20 results and 0 failures
[2025-02-10 02:17:33,812][flwr][INFO] - 
[2025-02-10 02:17:33,812][flwr][INFO] - [ROUND 5]
[2025-02-10 02:17:33,812][flwr][INFO] - configure_fit: strategy sampled 20 clients (out of 20)
[2025-02-10 02:17:59,599][flwr][INFO] - aggregate_fit: received 20 results and 0 failures
[2025-02-10 02:18:04,928][flwr][INFO] - fit progress: (5, 0.06831579332351685, {'accuracy': 0.4962}, 259.63158577500144)
[2025-02-10 02:18:04,928][flwr][INFO] - configure_evaluate: strategy sampled 20 clients (out of 20)
[2025-02-10 02:18:38,114][flwr][ERROR] - An exception was raised when processing a message by RayBackend
[2025-02-10 02:18:38,115][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=11805, ip=172.27.85.201, actor_id=d3adc0663baf2e1fe9cee7fe01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fef2c21af90>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=11805, ip=172.27.85.201, actor_id=d3adc0663baf2e1fe9cee7fe01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fef2c21af90>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 105, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=11805, ip=172.27.85.201, actor_id=d3adc0663baf2e1fe9cee7fe01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fef2c21af90>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c
[2025-02-10 02:18:38,117][flwr][ERROR] - Traceback (most recent call last):
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py", line 112, in worker
    out_mssg, updated_context = backend.process_message(message, context)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 187, in process_message
    raise ex
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 175, in process_message
    ) = self.pool.fetch_result_and_return_actor_to_pool(future)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 478, in fetch_result_and_return_actor_to_pool
    _, out_mssg, updated_context = ray.get(future)
                                   ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=11805, ip=172.27.85.201, actor_id=d3adc0663baf2e1fe9cee7fe01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fef2c21af90>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=11805, ip=172.27.85.201, actor_id=d3adc0663baf2e1fe9cee7fe01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fef2c21af90>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 105, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=11805, ip=172.27.85.201, actor_id=d3adc0663baf2e1fe9cee7fe01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fef2c21af90>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

[2025-02-10 02:18:38,202][flwr][INFO] - aggregate_evaluate: received 19 results and 1 failures
[2025-02-10 02:18:38,202][flwr][INFO] - 
[2025-02-10 02:18:38,203][flwr][INFO] - [ROUND 6]
[2025-02-10 02:18:38,203][flwr][INFO] - configure_fit: strategy sampled 20 clients (out of 20)
[2025-02-10 02:18:55,687][flwr][ERROR] - An exception was raised when processing a message by RayBackend
[2025-02-10 02:18:55,687][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=11806, ip=172.27.85.201, actor_id=015098502d9c55b4559aca2001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f275c17b8d0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=11806, ip=172.27.85.201, actor_id=015098502d9c55b4559aca2001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f275c17b8d0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 105, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=11806, ip=172.27.85.201, actor_id=015098502d9c55b4559aca2001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f275c17b8d0>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c
[2025-02-10 02:18:55,688][flwr][ERROR] - Traceback (most recent call last):
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py", line 112, in worker
    out_mssg, updated_context = backend.process_message(message, context)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 187, in process_message
    raise ex
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 175, in process_message
    ) = self.pool.fetch_result_and_return_actor_to_pool(future)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 478, in fetch_result_and_return_actor_to_pool
    _, out_mssg, updated_context = ray.get(future)
                                   ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=11806, ip=172.27.85.201, actor_id=015098502d9c55b4559aca2001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f275c17b8d0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=11806, ip=172.27.85.201, actor_id=015098502d9c55b4559aca2001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f275c17b8d0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 105, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=11806, ip=172.27.85.201, actor_id=015098502d9c55b4559aca2001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f275c17b8d0>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

[2025-02-10 02:19:21,035][flwr][INFO] - aggregate_fit: received 19 results and 1 failures
[2025-02-10 02:19:28,241][flwr][INFO] - fit progress: (6, 0.06573374679088592, {'accuracy': 0.5942}, 342.9447237259956)
[2025-02-10 02:19:28,241][flwr][INFO] - configure_evaluate: strategy sampled 20 clients (out of 20)
[2025-02-10 02:19:57,284][flwr][INFO] - aggregate_evaluate: received 20 results and 0 failures
[2025-02-10 02:19:57,284][flwr][INFO] - 
[2025-02-10 02:19:57,284][flwr][INFO] - [ROUND 7]
[2025-02-10 02:19:57,284][flwr][INFO] - configure_fit: strategy sampled 20 clients (out of 20)
[2025-02-10 02:20:25,133][flwr][INFO] - aggregate_fit: received 20 results and 0 failures
[2025-02-10 02:20:30,031][flwr][INFO] - fit progress: (7, 0.061899935376644136, {'accuracy': 0.6238}, 404.73462959800236)
[2025-02-10 02:20:30,031][flwr][INFO] - configure_evaluate: strategy sampled 20 clients (out of 20)
[2025-02-10 02:20:54,868][flwr][INFO] - aggregate_evaluate: received 20 results and 0 failures
[2025-02-10 02:20:54,869][flwr][INFO] - 
[2025-02-10 02:20:54,869][flwr][INFO] - [ROUND 8]
[2025-02-10 02:20:54,869][flwr][INFO] - configure_fit: strategy sampled 20 clients (out of 20)
[2025-02-10 02:21:21,809][flwr][INFO] - aggregate_fit: received 20 results and 0 failures
[2025-02-10 02:21:26,679][flwr][INFO] - fit progress: (8, 0.05680981584787369, {'accuracy': 0.6465}, 461.3825085759963)
[2025-02-10 02:21:26,679][flwr][INFO] - configure_evaluate: strategy sampled 20 clients (out of 20)
[2025-02-10 02:21:50,015][flwr][INFO] - aggregate_evaluate: received 20 results and 0 failures
[2025-02-10 02:21:50,015][flwr][INFO] - 
[2025-02-10 02:21:50,015][flwr][INFO] - [ROUND 9]
[2025-02-10 02:21:50,015][flwr][INFO] - configure_fit: strategy sampled 20 clients (out of 20)
[2025-02-10 02:22:15,569][flwr][INFO] - aggregate_fit: received 20 results and 0 failures
[2025-02-10 02:22:21,034][flwr][INFO] - fit progress: (9, 0.05082821489572525, {'accuracy': 0.6392}, 515.7378442639965)
[2025-02-10 02:22:21,035][flwr][INFO] - configure_evaluate: strategy sampled 20 clients (out of 20)
[2025-02-10 02:22:44,969][flwr][INFO] - aggregate_evaluate: received 20 results and 0 failures
[2025-02-10 02:22:44,970][flwr][INFO] - 
[2025-02-10 02:22:44,970][flwr][INFO] - [ROUND 10]
[2025-02-10 02:22:44,970][flwr][INFO] - configure_fit: strategy sampled 20 clients (out of 20)
[2025-02-10 02:23:10,935][flwr][INFO] - aggregate_fit: received 20 results and 0 failures
[2025-02-10 02:23:16,344][flwr][INFO] - fit progress: (10, 0.04499744917154312, {'accuracy': 0.6383}, 571.0473848129986)
[2025-02-10 02:23:16,344][flwr][INFO] - configure_evaluate: strategy sampled 20 clients (out of 20)
[2025-02-10 02:23:38,919][flwr][INFO] - aggregate_evaluate: received 20 results and 0 failures
[2025-02-10 02:23:38,919][flwr][INFO] - 
[2025-02-10 02:23:38,919][flwr][INFO] - [ROUND 11]
[2025-02-10 02:23:38,919][flwr][INFO] - configure_fit: strategy sampled 20 clients (out of 20)
[2025-02-10 02:24:04,006][flwr][INFO] - aggregate_fit: received 20 results and 0 failures
[2025-02-10 02:24:08,990][flwr][INFO] - fit progress: (11, 0.0397682650744915, {'accuracy': 0.6127}, 623.6934068959963)
[2025-02-10 02:24:08,990][flwr][INFO] - configure_evaluate: strategy sampled 20 clients (out of 20)
[2025-02-10 02:24:32,125][flwr][INFO] - aggregate_evaluate: received 20 results and 0 failures
[2025-02-10 02:24:32,125][flwr][INFO] - 
[2025-02-10 02:24:32,125][flwr][INFO] - [ROUND 12]
[2025-02-10 02:24:32,125][flwr][INFO] - configure_fit: strategy sampled 20 clients (out of 20)
[2025-02-10 02:24:57,664][flwr][INFO] - aggregate_fit: received 20 results and 0 failures
[2025-02-10 02:25:03,291][flwr][INFO] - fit progress: (12, 0.03560979931950569, {'accuracy': 0.6343}, 677.9948176510006)
[2025-02-10 02:25:03,292][flwr][INFO] - configure_evaluate: strategy sampled 20 clients (out of 20)
[2025-02-10 02:25:28,354][flwr][INFO] - aggregate_evaluate: received 20 results and 0 failures
[2025-02-10 02:25:28,355][flwr][INFO] - 
[2025-02-10 02:25:28,355][flwr][INFO] - [ROUND 13]
[2025-02-10 02:25:28,355][flwr][INFO] - configure_fit: strategy sampled 20 clients (out of 20)
[2025-02-10 02:25:53,840][flwr][INFO] - aggregate_fit: received 20 results and 0 failures
[2025-02-10 02:25:59,379][flwr][INFO] - fit progress: (13, 0.0320303096473217, {'accuracy': 0.6636}, 734.0825932469961)
[2025-02-10 02:25:59,379][flwr][INFO] - configure_evaluate: strategy sampled 20 clients (out of 20)
[2025-02-10 02:26:22,420][flwr][INFO] - aggregate_evaluate: received 20 results and 0 failures
[2025-02-10 02:26:22,420][flwr][INFO] - 
[2025-02-10 02:26:22,420][flwr][INFO] - [ROUND 14]
[2025-02-10 02:26:22,420][flwr][INFO] - configure_fit: strategy sampled 20 clients (out of 20)
[2025-02-10 02:26:52,515][flwr][INFO] - aggregate_fit: received 20 results and 0 failures
[2025-02-10 02:26:58,336][flwr][INFO] - fit progress: (14, 0.02995865940451622, {'accuracy': 0.6584}, 793.0394432710018)
[2025-02-10 02:26:58,336][flwr][INFO] - configure_evaluate: strategy sampled 20 clients (out of 20)
[2025-02-10 02:27:22,100][flwr][INFO] - aggregate_evaluate: received 20 results and 0 failures
[2025-02-10 02:27:22,100][flwr][INFO] - 
[2025-02-10 02:27:22,101][flwr][INFO] - [ROUND 15]
[2025-02-10 02:27:22,101][flwr][INFO] - configure_fit: strategy sampled 20 clients (out of 20)
[2025-02-10 02:27:47,385][flwr][INFO] - aggregate_fit: received 20 results and 0 failures
[2025-02-10 02:27:53,530][flwr][INFO] - fit progress: (15, 0.02800023330748081, {'accuracy': 0.6648}, 848.2331533799952)
[2025-02-10 02:27:53,530][flwr][INFO] - configure_evaluate: strategy sampled 20 clients (out of 20)
[2025-02-10 02:28:16,267][flwr][INFO] - aggregate_evaluate: received 20 results and 0 failures
[2025-02-10 02:28:16,267][flwr][INFO] - 
[2025-02-10 02:28:16,267][flwr][INFO] - [ROUND 16]
[2025-02-10 02:28:16,268][flwr][INFO] - configure_fit: strategy sampled 20 clients (out of 20)
[2025-02-10 02:28:41,440][flwr][INFO] - aggregate_fit: received 20 results and 0 failures
[2025-02-10 02:28:46,793][flwr][INFO] - fit progress: (16, 0.025705383267998694, {'accuracy': 0.7049}, 901.4964438819952)
[2025-02-10 02:28:46,793][flwr][INFO] - configure_evaluate: strategy sampled 20 clients (out of 20)
[2025-02-10 02:29:09,527][flwr][INFO] - aggregate_evaluate: received 20 results and 0 failures
[2025-02-10 02:29:09,527][flwr][INFO] - 
[2025-02-10 02:29:09,527][flwr][INFO] - [ROUND 17]
[2025-02-10 02:29:09,528][flwr][INFO] - configure_fit: strategy sampled 20 clients (out of 20)
[2025-02-10 02:29:35,216][flwr][INFO] - aggregate_fit: received 20 results and 0 failures
[2025-02-10 02:29:40,568][flwr][INFO] - fit progress: (17, 0.0246509042263031, {'accuracy': 0.7099}, 955.2717548189976)
[2025-02-10 02:29:40,569][flwr][INFO] - configure_evaluate: strategy sampled 20 clients (out of 20)
[2025-02-10 02:30:03,701][flwr][INFO] - aggregate_evaluate: received 20 results and 0 failures
[2025-02-10 02:30:03,701][flwr][INFO] - 
[2025-02-10 02:30:03,701][flwr][INFO] - [ROUND 18]
[2025-02-10 02:30:03,701][flwr][INFO] - configure_fit: strategy sampled 20 clients (out of 20)
[2025-02-10 02:30:28,480][flwr][INFO] - aggregate_fit: received 20 results and 0 failures
[2025-02-10 02:30:33,359][flwr][INFO] - fit progress: (18, 0.023191045105457306, {'accuracy': 0.7357}, 1008.0626258209959)
[2025-02-10 02:30:33,359][flwr][INFO] - configure_evaluate: strategy sampled 20 clients (out of 20)
[2025-02-10 02:30:58,097][flwr][INFO] - aggregate_evaluate: received 20 results and 0 failures
[2025-02-10 02:30:58,097][flwr][INFO] - 
[2025-02-10 02:30:58,097][flwr][INFO] - [ROUND 19]
[2025-02-10 02:30:58,097][flwr][INFO] - configure_fit: strategy sampled 20 clients (out of 20)
[2025-02-10 02:31:23,246][flwr][INFO] - aggregate_fit: received 20 results and 0 failures
[2025-02-10 02:31:28,229][flwr][INFO] - fit progress: (19, 0.022335791736841203, {'accuracy': 0.7455}, 1062.932420860001)
[2025-02-10 02:31:28,229][flwr][INFO] - configure_evaluate: strategy sampled 20 clients (out of 20)
[2025-02-10 02:31:51,364][flwr][INFO] - aggregate_evaluate: received 20 results and 0 failures
[2025-02-10 02:31:51,364][flwr][INFO] - 
[2025-02-10 02:31:51,364][flwr][INFO] - [ROUND 20]
[2025-02-10 02:31:51,365][flwr][INFO] - configure_fit: strategy sampled 20 clients (out of 20)
[2025-02-10 02:32:18,308][flwr][INFO] - aggregate_fit: received 20 results and 0 failures
[2025-02-10 02:32:23,248][flwr][INFO] - fit progress: (20, 0.021397429314255714, {'accuracy': 0.761}, 1117.9511894530006)
[2025-02-10 02:32:23,248][flwr][INFO] - configure_evaluate: strategy sampled 20 clients (out of 20)
[2025-02-10 02:32:46,688][flwr][INFO] - aggregate_evaluate: received 20 results and 0 failures
[2025-02-10 02:32:46,689][flwr][INFO] - 
[2025-02-10 02:32:46,689][flwr][INFO] - [SUMMARY]
[2025-02-10 02:32:46,689][flwr][INFO] - Run finished 20 round(s) in 1141.39s
[2025-02-10 02:32:46,690][flwr][INFO] - 	History (loss, distributed):
[2025-02-10 02:32:46,690][flwr][INFO] - 		round 1: 0.07655571440855662
[2025-02-10 02:32:46,690][flwr][INFO] - 		round 2: 0.0761999519666036
[2025-02-10 02:32:46,690][flwr][INFO] - 		round 3: 0.07558153847853344
[2025-02-10 02:32:46,690][flwr][INFO] - 		round 4: 0.07459344387054444
[2025-02-10 02:32:46,690][flwr][INFO] - 		round 5: 0.07283591994068078
[2025-02-10 02:32:46,690][flwr][INFO] - 		round 6: 0.0701492847998937
[2025-02-10 02:32:46,690][flwr][INFO] - 		round 7: 0.06618401313821475
[2025-02-10 02:32:46,690][flwr][INFO] - 		round 8: 0.06086817502975465
[2025-02-10 02:32:46,690][flwr][INFO] - 		round 9: 0.05464572807153066
[2025-02-10 02:32:46,691][flwr][INFO] - 		round 10: 0.04854320074121158
[2025-02-10 02:32:46,691][flwr][INFO] - 		round 11: 0.04304153243700663
[2025-02-10 02:32:46,691][flwr][INFO] - 		round 12: 0.03878043932219346
[2025-02-10 02:32:46,691][flwr][INFO] - 		round 13: 0.034913811832666404
[2025-02-10 02:32:46,691][flwr][INFO] - 		round 14: 0.03288093994061152
[2025-02-10 02:32:46,691][flwr][INFO] - 		round 15: 0.030717027112841605
[2025-02-10 02:32:46,691][flwr][INFO] - 		round 16: 0.02838156605760257
[2025-02-10 02:32:46,691][flwr][INFO] - 		round 17: 0.027312454854448637
[2025-02-10 02:32:46,691][flwr][INFO] - 		round 18: 0.025740591151018944
[2025-02-10 02:32:46,691][flwr][INFO] - 		round 19: 0.02478610278417667
[2025-02-10 02:32:46,691][flwr][INFO] - 		round 20: 0.02367408255736033
[2025-02-10 02:32:46,691][flwr][INFO] - 	History (loss, centralized):
[2025-02-10 02:32:46,691][flwr][INFO] - 		round 0: 0.07214015040397644
[2025-02-10 02:32:46,692][flwr][INFO] - 		round 1: 0.07187389771938324
[2025-02-10 02:32:46,692][flwr][INFO] - 		round 2: 0.07153169589042664
[2025-02-10 02:32:46,692][flwr][INFO] - 		round 3: 0.07093953688144684
[2025-02-10 02:32:46,692][flwr][INFO] - 		round 4: 0.06998767564296722
[2025-02-10 02:32:46,692][flwr][INFO] - 		round 5: 0.06831579332351685
[2025-02-10 02:32:46,692][flwr][INFO] - 		round 6: 0.06573374679088592
[2025-02-10 02:32:46,692][flwr][INFO] - 		round 7: 0.061899935376644136
[2025-02-10 02:32:46,692][flwr][INFO] - 		round 8: 0.05680981584787369
[2025-02-10 02:32:46,692][flwr][INFO] - 		round 9: 0.05082821489572525
[2025-02-10 02:32:46,692][flwr][INFO] - 		round 10: 0.04499744917154312
[2025-02-10 02:32:46,692][flwr][INFO] - 		round 11: 0.0397682650744915
[2025-02-10 02:32:46,692][flwr][INFO] - 		round 12: 0.03560979931950569
[2025-02-10 02:32:46,693][flwr][INFO] - 		round 13: 0.0320303096473217
[2025-02-10 02:32:46,693][flwr][INFO] - 		round 14: 0.02995865940451622
[2025-02-10 02:32:46,693][flwr][INFO] - 		round 15: 0.02800023330748081
[2025-02-10 02:32:46,693][flwr][INFO] - 		round 16: 0.025705383267998694
[2025-02-10 02:32:46,693][flwr][INFO] - 		round 17: 0.0246509042263031
[2025-02-10 02:32:46,693][flwr][INFO] - 		round 18: 0.023191045105457306
[2025-02-10 02:32:46,693][flwr][INFO] - 		round 19: 0.022335791736841203
[2025-02-10 02:32:46,693][flwr][INFO] - 		round 20: 0.021397429314255714
[2025-02-10 02:32:46,693][flwr][INFO] - 	History (metrics, distributed, fit):
[2025-02-10 02:32:46,693][flwr][INFO] - 	{'clients_epsilons': [(1, 0.6813471387867438),
[2025-02-10 02:32:46,693][flwr][INFO] - 	                      (2, 0.6813471387867438),
[2025-02-10 02:32:46,693][flwr][INFO] - 	                      (3, 0.6813471387867438),
[2025-02-10 02:32:46,694][flwr][INFO] - 	                      (4, 0.6813471387867438),
[2025-02-10 02:32:46,694][flwr][INFO] - 	                      (5, 0.6813471387867438),
[2025-02-10 02:32:46,694][flwr][INFO] - 	                      (6, 0.6813471387867437),
[2025-02-10 02:32:46,694][flwr][INFO] - 	                      (7, 0.6813471387867438),
[2025-02-10 02:32:46,694][flwr][INFO] - 	                      (8, 0.6813471387867438),
[2025-02-10 02:32:46,694][flwr][INFO] - 	                      (9, 0.6813471387867438),
[2025-02-10 02:32:46,694][flwr][INFO] - 	                      (10, 0.6813471387867438),
[2025-02-10 02:32:46,694][flwr][INFO] - 	                      (11, 0.6813471387867438),
[2025-02-10 02:32:46,694][flwr][INFO] - 	                      (12, 0.6813471387867438),
[2025-02-10 02:32:46,694][flwr][INFO] - 	                      (13, 0.6813471387867438),
[2025-02-10 02:32:46,694][flwr][INFO] - 	                      (14, 0.6813471387867438),
[2025-02-10 02:32:46,695][flwr][INFO] - 	                      (15, 0.6813471387867438),
[2025-02-10 02:32:46,695][flwr][INFO] - 	                      (16, 0.6813471387867438),
[2025-02-10 02:32:46,695][flwr][INFO] - 	                      (17, 0.6813471387867438),
[2025-02-10 02:32:46,695][flwr][INFO] - 	                      (18, 0.6813471387867438),
[2025-02-10 02:32:46,695][flwr][INFO] - 	                      (19, 0.6813471387867438),
[2025-02-10 02:32:46,695][flwr][INFO] - 	                      (20, 0.6813471387867438)],
[2025-02-10 02:32:46,695][flwr][INFO] - 	 'clients_losses': [(1, 2.3020098972320557),
[2025-02-10 02:32:46,695][flwr][INFO] - 	                    (2, 2.2929678853352864),
[2025-02-10 02:32:46,695][flwr][INFO] - 	                    (3, 2.279997099240621),
[2025-02-10 02:32:46,695][flwr][INFO] - 	                    (4, 2.2582794427871704),
[2025-02-10 02:32:46,696][flwr][INFO] - 	                    (5, 2.221821237405141),
[2025-02-10 02:32:46,696][flwr][INFO] - 	                    (6, 2.161288238826551),
[2025-02-10 02:32:46,696][flwr][INFO] - 	                    (7, 2.06686998407046),
[2025-02-10 02:32:46,696][flwr][INFO] - 	                    (8, 1.933751339117686),
[2025-02-10 02:32:46,696][flwr][INFO] - 	                    (9, 1.766944659948349),
[2025-02-10 02:32:46,696][flwr][INFO] - 	                    (10, 1.581799288193385),
[2025-02-10 02:32:46,696][flwr][INFO] - 	                    (11, 1.4078436013062794),
[2025-02-10 02:32:46,696][flwr][INFO] - 	                    (12, 1.2570341002941132),
[2025-02-10 02:32:46,696][flwr][INFO] - 	                    (13, 1.1331241230169933),
[2025-02-10 02:32:46,696][flwr][INFO] - 	                    (14, 1.0349429072936376),
[2025-02-10 02:32:46,696][flwr][INFO] - 	                    (15, 0.9722647214929263),
[2025-02-10 02:32:46,696][flwr][INFO] - 	                    (16, 0.9095388283332189),
[2025-02-10 02:32:46,697][flwr][INFO] - 	                    (17, 0.855143907268842),
[2025-02-10 02:32:46,697][flwr][INFO] - 	                    (18, 0.8148671387632688),
[2025-02-10 02:32:46,697][flwr][INFO] - 	                    (19, 0.7778601799408594),
[2025-02-10 02:32:46,697][flwr][INFO] - 	                    (20, 0.7560425414641698)]}
[2025-02-10 02:32:46,697][flwr][INFO] - 	History (metrics, distributed, evaluate):
[2025-02-10 02:32:46,697][flwr][INFO] - 	{'clients_accuracies': [(1, 0.16624999999999998),
[2025-02-10 02:32:46,697][flwr][INFO] - 	                        (2, 0.19625),
[2025-02-10 02:32:46,697][flwr][INFO] - 	                        (3, 0.20166666666666672),
[2025-02-10 02:32:46,697][flwr][INFO] - 	                        (4, 0.2979166666666667),
[2025-02-10 02:32:46,697][flwr][INFO] - 	                        (5, 0.4868421052631579),
[2025-02-10 02:32:46,697][flwr][INFO] - 	                        (6, 0.6025),
[2025-02-10 02:32:46,697][flwr][INFO] - 	                        (7, 0.625),
[2025-02-10 02:32:46,697][flwr][INFO] - 	                        (8, 0.64625),
[2025-02-10 02:32:46,698][flwr][INFO] - 	                        (9, 0.6304166666666668),
[2025-02-10 02:32:46,698][flwr][INFO] - 	                        (10, 0.6279166666666666),
[2025-02-10 02:32:46,698][flwr][INFO] - 	                        (11, 0.6066666666666667),
[2025-02-10 02:32:46,698][flwr][INFO] - 	                        (12, 0.6241666666666666),
[2025-02-10 02:32:46,698][flwr][INFO] - 	                        (13, 0.655),
[2025-02-10 02:32:46,698][flwr][INFO] - 	                        (14, 0.6525),
[2025-02-10 02:32:46,698][flwr][INFO] - 	                        (15, 0.6620833333333334),
[2025-02-10 02:32:46,698][flwr][INFO] - 	                        (16, 0.6966666666666668),
[2025-02-10 02:32:46,698][flwr][INFO] - 	                        (17, 0.7008333333333332),
[2025-02-10 02:32:46,698][flwr][INFO] - 	                        (18, 0.7195833333333332),
[2025-02-10 02:32:46,698][flwr][INFO] - 	                        (19, 0.7366666666666667),
[2025-02-10 02:32:46,698][flwr][INFO] - 	                        (20, 0.7512500000000001)],
[2025-02-10 02:32:46,699][flwr][INFO] - 	 'clients_losses': [(1, 0.07655571440855662),
[2025-02-10 02:32:46,699][flwr][INFO] - 	                    (2, 0.0761999519666036),
[2025-02-10 02:32:46,699][flwr][INFO] - 	                    (3, 0.07558153847853344),
[2025-02-10 02:32:46,699][flwr][INFO] - 	                    (4, 0.07459344387054444),
[2025-02-10 02:32:46,699][flwr][INFO] - 	                    (5, 0.07283591994068078),
[2025-02-10 02:32:46,699][flwr][INFO] - 	                    (6, 0.0701492847998937),
[2025-02-10 02:32:46,699][flwr][INFO] - 	                    (7, 0.06618401313821475),
[2025-02-10 02:32:46,699][flwr][INFO] - 	                    (8, 0.06086817502975465),
[2025-02-10 02:32:46,699][flwr][INFO] - 	                    (9, 0.05464572807153066),
[2025-02-10 02:32:46,699][flwr][INFO] - 	                    (10, 0.04854320074121158),
[2025-02-10 02:32:46,699][flwr][INFO] - 	                    (11, 0.04304153243700663),
[2025-02-10 02:32:46,699][flwr][INFO] - 	                    (12, 0.03878043932219346),
[2025-02-10 02:32:46,699][flwr][INFO] - 	                    (13, 0.034913811832666404),
[2025-02-10 02:32:46,700][flwr][INFO] - 	                    (14, 0.03288093994061152),
[2025-02-10 02:32:46,700][flwr][INFO] - 	                    (15, 0.030717027112841605),
[2025-02-10 02:32:46,700][flwr][INFO] - 	                    (16, 0.02838156605760257),
[2025-02-10 02:32:46,700][flwr][INFO] - 	                    (17, 0.027312454854448637),
[2025-02-10 02:32:46,700][flwr][INFO] - 	                    (18, 0.025740591151018944),
[2025-02-10 02:32:46,700][flwr][INFO] - 	                    (19, 0.02478610278417667),
[2025-02-10 02:32:46,700][flwr][INFO] - 	                    (20, 0.02367408255736033)]}
[2025-02-10 02:32:46,700][flwr][INFO] - 	History (metrics, centralized):
[2025-02-10 02:32:46,700][flwr][INFO] - 	{'accuracy': [(0, 0.0988),
[2025-02-10 02:32:46,700][flwr][INFO] - 	              (1, 0.1655),
[2025-02-10 02:32:46,701][flwr][INFO] - 	              (2, 0.1957),
[2025-02-10 02:32:46,701][flwr][INFO] - 	              (3, 0.2046),
[2025-02-10 02:32:46,701][flwr][INFO] - 	              (4, 0.3171),
[2025-02-10 02:32:46,701][flwr][INFO] - 	              (5, 0.4962),
[2025-02-10 02:32:46,701][flwr][INFO] - 	              (6, 0.5942),
[2025-02-10 02:32:46,701][flwr][INFO] - 	              (7, 0.6238),
[2025-02-10 02:32:46,701][flwr][INFO] - 	              (8, 0.6465),
[2025-02-10 02:32:46,701][flwr][INFO] - 	              (9, 0.6392),
[2025-02-10 02:32:46,701][flwr][INFO] - 	              (10, 0.6383),
[2025-02-10 02:32:46,701][flwr][INFO] - 	              (11, 0.6127),
[2025-02-10 02:32:46,701][flwr][INFO] - 	              (12, 0.6343),
[2025-02-10 02:32:46,701][flwr][INFO] - 	              (13, 0.6636),
[2025-02-10 02:32:46,702][flwr][INFO] - 	              (14, 0.6584),
[2025-02-10 02:32:46,702][flwr][INFO] - 	              (15, 0.6648),
[2025-02-10 02:32:46,702][flwr][INFO] - 	              (16, 0.7049),
[2025-02-10 02:32:46,702][flwr][INFO] - 	              (17, 0.7099),
[2025-02-10 02:32:46,702][flwr][INFO] - 	              (18, 0.7357),
[2025-02-10 02:32:46,702][flwr][INFO] - 	              (19, 0.7455),
[2025-02-10 02:32:46,702][flwr][INFO] - 	              (20, 0.761)]}
[2025-02-10 02:32:46,702][flwr][INFO] - 
